---
title: "PORTFOLIO OPTIMIZATION"
output: html_notebook
---

- Of the 69 possible dividend stocks to invest in, build 3 portfolios of 12 stocks each. 
  - Set Criteria (high expected return, lower risk, Sharpe ratio)
  
- Best way to optimize Adding to positions (going off of Ex-div) 

- Financial analyst job skills (outside of stock market)

Each portfolio must has one S&P 500 Index (SPY, VOO, or IVV)

12 Month Treasury Yield as of 05/03/2021 is 0.05%

```{r}
library(quantmod)
library(fPortfolio)
library(PerformanceAnalytics)
library(gtools)
library(tidyr)
```



```{r}
# Save Tickers to a vector
TICKERS <- c("CLX", "GIS", "TROW", "V", "AXP",  "USB" , "STOR" ,"MA"  , "MSFT" ,"UPS" , "DOW" , "MRK" , "LMT" , "KMB" , "INTC", "SBUX", "KHC" , "SPG" , "FRT",  "STAG", "MAIN" ,"PBCT", "GD" ,  "ESS" , "ITW" , "AVGO", "WMT" , "TGT" , "AAPL" ,"BAC" , "WFC" , "WPC"  ,"QCOM" ,"DIS" , "WM" ,  "WBA" , "VTI", "CL" ,  "CHD" , "PPG" , "NEE",  "PG" ,  "MCD",  "PSX",  "APD" , "DUK" , "NTB"  ,"MMM",  "GPC" , "JNJ",  "IBM" , "VZ" ,  "VNQ",  "CAT" , "ATO" , "LEG",  "ABBV", "PEP" , "ADP" , "XOM" , "T" ,   "CSCO" ,"ED" ,  "JPM",  "LOW" , "KO"  , "CVX" , "O" ,   "PFE" ) 
TICKERS <- sort(TICKERS, decreasing = F)

# Define the monthly risk free rate 
monthly_risk_free_rate <- (0.05 / 100) / 12

```

```{r}
for (SYMBOL in TICKERS)   {
getSymbols( SYMBOL , from = Sys.Date()-5*365 , to= Sys.Date() , auto.assign = F) -> PRICE
monthlyReturn(PRICE[,6]) -> RETURN
if( SYMBOL==TICKERS[1])   { RETURN -> TICKER_MONTHLY_RETURNS }
else { cbind(TICKER_MONTHLY_RETURNS,RETURN) -> TICKER_MONTHLY_RETURNS }
}

TICKERS -> colnames(TICKER_MONTHLY_RETURNS)

TICKERS <- na.omit(TICKERS)

head(TICKER_MONTHLY_RETURNS)
```



```{r}
ticker_list <- c("CLX", "GIS", "TROW", "V", "AXP",  "USB" , "STOR" ,"MA"  , "MSFT" ,"UPS" , "DOW" , "MRK" , "LMT" , "KMB" , "INTC", "SBUX", "KHC" , "SPG" , "FRT",  "STAG", "MAIN" ,"PBCT", "GD" ,  "ESS" , "ITW" , "AVGO", "WMT" , "TGT" , "AAPL" ,"BAC" , "WFC" , "WPC"  ,"QCOM" ,"DIS" , "WM" ,  "WBA" , "VTI", "CL" ,  "CHD" , "PPG" , "NEE",  "PG" ,  "MCD",  "PSX",  "APD" , "DUK" , "NTB"  ,"MMM",  "GPC" , "JNJ",  "IBM" , "VZ" ,  "VNQ",  "CAT" , "ATO" , "LEG",  "ABBV", "PEP" , "ADP" , "XOM" , "T" ,   "CSCO" ,"ED" ,  "JPM",  "LOW" , "KO"  , "CVX" , "O" ,   "PFE" ) 

format(factorial(length(ticker_list)) / (factorial(12) * factorial((length(ticker_list)-12))),scientific = F)
```



